### ISSUE TITLE
Player Entity

### ISSUE THREAD

**Issue by uo287841** [Arquisoft/wiq_en1a#28]
I was wondering what attributes would the player class have in camparison to the client class.

**Comment by ChristianFN2** [comment]
Depending on the answer I get in #12, client could be unnecessary, since we would not need to show information to any client, just manage the game with the APIs and show past scores of the playing user.

So, at least for the User entity, I think we would need the login/registration info, so the username and password (encrypted) and then link it to the past scores (GameScore entity). The latter should have date of recording, number of correct answers, number of incorrect answers and time taken for completion for now. We could add more attributes later if we need them.

(Regardless of the answer of #12, I think the client would still be secondary (The main is the game), so we should start with the player for the first deliverable)

**Comment by adriiglz** [comment]
I added a rankings property and now the user model stores some info about their games for rankings functionallity. I have pushed the branch and will do a PR when I have finished developing the ranking
